# -*- coding: utf-8 -*-
"""MAT3535-Hafta8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgagiRkNtUZyCRRWfomE0elqBVYZiqwQ

# **Matrisin Biçimsel Formatı**
"""

import numpy as np

# 2x3'lük bir matris (2 satır, 3 sütun)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Matris A:\n", A)
print("Boyut (Shape):", A.shape)
print("Veri Tipi:", A.dtype)

# 3x3'lük Sıfır Matrisi
sifir_matrisi = np.zeros((3, 3))

# 3x3'lük Birler Matrisi
birler_matrisi = np.ones((3, 3))

# 3x3'lük Birim Matris (Identity Matrix)
birim_matris = np.eye(3)

print("Sıfır Matrisi:\n", sifir_matrisi)
print("Birler Matrisi:\n", birler_matrisi)
print("Birim Matrisi:\n", birim_matris)

A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])

# Toplama
C = A + B

# Skaler Çarpım (Bir sayıyla çarpma)
# Matrisin her elemanını 2 ile çarpar
D = A * 2

print("Toplam (A+B):\n", C)
print("Skaler Çarpım (2A):\n", D)

A = np.array([[1, 2],
              [3, 4]]) # 2x2

B = np.array([[5, 6],
              [7, 8]]) # 2x2

# YANLIŞ YÖNTEM (Nümerik analiz için genelde istenmeyen)
# eleman_bazli = A * B

# DOĞRU YÖNTEM (Matris Çarpımı)
carpim_1 = np.dot(A, B)
# VEYA (Modern Python kullanımı)
carpim_2 = A @ B

print("Matris Çarpımı (A @ B):\n", carpim_2)

M = np.array([[1, 2],
              [3, 4]])

print("Matrisin orijinali:\n", M)

# 1. Transpoze
print("Transpoze:\n", M.T)

# 2. Determinant
det_M = np.linalg.det(M)
print(f"Determinant: {det_M:.2f}")

# 3. Ters Matris (Inverse)
# Determinant 0 değilse hesaplanır
if det_M != 0:
    inv_M = np.linalg.inv(M)
    print("Ters Matris:\n", inv_M)

    # Sağlama: M ile Tersi'nin çarpımı Birim Matris olmalı
    print("Sağlama (M @ inv_M):\n", np.round(M @ inv_M))

# Katsayılar Matrisi
A = np.array([[2, 1],
              [3, 4]])

# Sonuç Vektörü
b = np.array([8, 18])

# Çözüm (x ve y değerleri)
# np.linalg.solve() fonksiyonu en optimize yoldur (Ters matris almaktan daha hızlıdır)
cozum = np.linalg.solve(A, b)

print(f"x değeri: {cozum[0]}")
print(f"y değeri: {cozum[1]}")

import numpy as np
import time
N = 200
print(f"{N}x{N} boyutunda iki matris oluşturuluyor...")
A = np.random.rand(N, N)
B = np.random.rand(N, N)
C_numpy = np.zeros((N, N))
C_loop = np.zeros((N, N))
print("-" * 40)
print("1. Yöntem: 'For' döngüleri ile hesaplanıyor... ")
start_loop = time.time()
for i in range(N):          # A'nın satırları
    for j in range(N):      # B'nin sütunları
        for k in range(N):  # Ortak boyut
            C_loop[i][j] += A[i][k] * B[k][j]
end_loop = time.time()
sure_loop = end_loop - start_loop
print(f"Bitti! Döngü Süresi: {sure_loop:.4f} saniye")
print("\n2. Yöntem: NumPy ile hesaplanıyor...")
start_numpy = time.time()
C_numpy = np.dot(A, B) # Alternatif: A @ B
end_numpy = time.time()
sure_numpy = end_numpy - start_numpy
print(f"Bitti! NumPy Süresi: {sure_numpy:.4f} saniye")
print("-" * 40)
hiz_farki = sure_loop / sure_numpy
print(f"\nSONUÇ: NumPy, klasik döngülerden {hiz_farki:.1f} KAT daha hızlı.")

import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 2, 3])
y = np.array([2, 3, 5])

A = np.vstack([np.ones(len(x)), x]).T
print("A Matrisi (Design Matrix):\n", A)
print("\ny Vektörü:\n", y)

A_T = A.T
A_T_A = A_T @ A       # Katsayılar matrisi
A_T_y = A_T @ y       # Sonuç vektörü

# Denklem sistemini çöz
katsayilar = np.linalg.solve(A_T_A, A_T_y)

a = katsayilar[0]
b = katsayilar[1]

print("-" * 30)
print(f"Hesaplanan Sabit (a): {a:.4f}")
print(f"Hesaplanan Eğim (b):  {b:.4f}")
print(f"\nDENKLEM: y = {b:.4f}x + {a:.4f}")
print("-" * 30)

# Doğruyu çizmek için x noktaları oluştur
x_line = np.linspace(0, 4, 100)
y_line = a + b * x_line
plt.figure(figsize=(8, 5))
# Orijinal noktaları çiz
plt.scatter(x, y, color='red', s=100, label='Verilen Noktalar (1,2), (2,3), (3,5)')
# Bulduğumuz en iyi doğruyu çiz
plt.plot(x_line, y_line, color='blue', linewidth=2, label=f'En Küçük Kareler Doğrusu\ny = {b:.2f}x + {a:.2f}')
plt.title('En Küçük Kareler Yöntemi ile Doğru Uydurma')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()